[package]
name = "py-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Generate Python dataclass and Enum bindings from Rust types"

[dependencies]
py-rs-macros = { path = "../py-rs-macros", version = "0.1.0" }
bytes = { version = "1", optional = true }
chrono = { version = "0.4", default-features = false, optional = true }
serde_json = { version = "1", optional = true }
url = { version = "2", default-features = false, optional = true }
uuid = { version = "1", optional = true }

[features]
default = []
bytes-impl = ["dep:bytes"]
chrono-impl = ["dep:chrono"]
serde-json-impl = ["dep:serde_json"]
url-impl = ["dep:url"]
uuid-impl = ["dep:uuid"]
