//! Generate Python model declarations from Rust types.
//!
//! Derive [`PY`] on a struct or enum, then call [`PY::export_all`] or add
//! `#[py(export)]` to generate bindings during `cargo test`.

use std::any::TypeId;
use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::fmt;
use std::fs;
use std::path::{Component, Path, PathBuf};

pub use py_rs_macros::PY;

const HEADER: &str = "# This file was generated by py-rs. Do not edit.\n";

/// An exported Rust type referred to by another type.
#[derive(Clone)]
pub struct Dependency {
    id: TypeId,
    name: String,
    path: PathBuf,
    render: fn() -> Result<String, ExportError>,
    export: fn(&Path) -> Result<(), ExportError>,
    children: fn() -> Vec<Dependency>,
}

/// Errors produced while generating Python files.
#[derive(Debug)]
pub enum ExportError {
    NotExportable(&'static str),
    InvalidPath(PathBuf),
    ConflictingFile(PathBuf),
    NameCollision(String),
    Io(std::io::Error),
}

impl fmt::Display for ExportError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NotExportable(name) => write!(f, "{name} has no Python declaration"),
            Self::InvalidPath(path) => write!(f, "invalid export path: {}", path.display()),
            Self::ConflictingFile(path) => write!(
                f,
                "refusing to overwrite a file owned by another type: {}",
                path.display()
            ),
            Self::NameCollision(name) => write!(f, "conflicting Python type name: {name}"),
            Self::Io(err) => err.fmt(f),
        }
    }
}

impl std::error::Error for ExportError {}

impl From<std::io::Error> for ExportError {
    fn from(value: std::io::Error) -> Self {
        Self::Io(value)
    }
}

/// Describes a Python representation of a Rust type.
///
/// Container implementations such as `Option<T>` and `Vec<T>` contribute
/// referenced types; derived structs and enums contribute their own fields.
pub trait PY: 'static {
    fn name() -> String;
    fn inline() -> String;
    fn decl() -> String {
        String::new()
    }
    fn dependencies() -> Vec<Dependency> {
        Vec::new()
    }
    fn output_path() -> Option<PathBuf> {
        None
    }
    fn declaration_names() -> Vec<String> {
        vec![Self::name()]
    }

    /// Types referred to by this type when it appears in a field.
    fn referenced_types() -> Vec<Dependency>
    where
        Self: Sized,
    {
        Self::dependency().into_iter().collect()
    }

    fn dependency() -> Option<Dependency>
    where
        Self: Sized,
    {
        Self::output_path().map(|path| Dependency {
            id: TypeId::of::<Self>(),
            name: Self::name(),
            path,
            render: render::<Self>,
            export: export_one::<Self>,
            children: Self::dependencies,
        })
    }

    /// Render one Python module, including its imports.
    fn export_to_string() -> Result<String, ExportError>
    where
        Self: Sized,
    {
        render::<Self>()
    }

    /// Write this declaration to `bindings/<name>.py` (or `#[py(export_to)]`).
    fn export() -> Result<(), ExportError>
    where
        Self: Sized,
    {
        export_one::<Self>(&export_dir())
    }

    /// Export this type and all of its transitive dependencies.
    fn export_all() -> Result<(), ExportError>
    where
        Self: Sized,
    {
        let dir = export_dir();
        let mut seen = HashSet::new();
        let mut paths = HashMap::new();
        let mut planned = Vec::new();
        let mut pending =
            vec![Self::dependency()
                .ok_or(ExportError::NotExportable(std::any::type_name::<Self>()))?];
        while let Some(dep) = pending.pop() {
            if seen.insert(dep.id) {
                validate_path(&dep.path)?;
                if paths
                    .insert(dep.path.clone(), dep.id)
                    .is_some_and(|id| id != dep.id)
                {
                    return Err(ExportError::ConflictingFile(dir.join(dep.path)));
                }
                (dep.render)()?;
                pending.extend((dep.children)());
                planned.push(dep);
            }
        }
        for dep in planned {
            (dep.export)(&dir)?;
        }
        Ok(())
    }
}

fn export_dir() -> PathBuf {
    std::env::var_os("PY_RS_EXPORT_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("bindings"))
}

fn validate_path(path: &Path) -> Result<(), ExportError> {
    if path.extension().and_then(|x| x.to_str()) != Some("py")
        || path
            .components()
            .any(|c| !matches!(c, Component::Normal(_)))
    {
        return Err(ExportError::InvalidPath(path.to_path_buf()));
    }
    let mut parts = path
        .components()
        .map(|c| c.as_os_str().to_string_lossy().into_owned())
        .collect::<Vec<_>>();
    let module = parts.pop().unwrap_or_default();
    let module = module.strip_suffix(".py").unwrap_or("");
    if module == "__init__"
        || !valid_module_name(module)
        || parts.iter().any(|part| !valid_module_name(part))
    {
        return Err(ExportError::InvalidPath(path.to_path_buf()));
    }
    Ok(())
}

fn valid_module_name(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !matches!(
            name,
            "False"
                | "None"
                | "True"
                | "and"
                | "as"
                | "assert"
                | "async"
                | "await"
                | "break"
                | "class"
                | "continue"
                | "def"
                | "del"
                | "elif"
                | "else"
                | "except"
                | "finally"
                | "for"
                | "from"
                | "global"
                | "if"
                | "import"
                | "in"
                | "is"
                | "lambda"
                | "nonlocal"
                | "not"
                | "or"
                | "pass"
                | "raise"
                | "return"
                | "try"
                | "while"
                | "with"
                | "yield"
        )
}

fn export_one<T: PY>(dir: &Path) -> Result<(), ExportError> {
    let relative =
        T::output_path().ok_or(ExportError::NotExportable(std::any::type_name::<T>()))?;
    validate_path(&relative)?;
    let path = dir.join(&relative);
    let content = render::<T>()?;
    match fs::read_to_string(&path) {
        Ok(existing) => {
            let owner = format!("# Rust type: {}\n", std::any::type_name::<T>());
            if !existing.starts_with(&(HEADER.to_owned() + &owner)) {
                return Err(ExportError::ConflictingFile(path));
            }
            if existing == content {
                return Ok(());
            }
        }
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
        Err(err) => return Err(ExportError::Io(err)),
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    // Package markers make relative imports work for both root and nested files.
    let mut package = path.parent();
    while let Some(folder) = package {
        if !folder.starts_with(dir) {
            break;
        }
        let marker = folder.join("__init__.py");
        if !marker.exists() {
            fs::write(&marker, "")?;
        }
        if folder == dir {
            break;
        }
        package = folder.parent();
    }
    fs::write(path, content)?;
    Ok(())
}

fn render<T: PY>() -> Result<String, ExportError> {
    let own = T::output_path().ok_or(ExportError::NotExportable(std::any::type_name::<T>()))?;
    validate_path(&own)?;
    let mut imports: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    let mut names: HashMap<String, TypeId> = T::declaration_names()
        .into_iter()
        .map(|name| (name, TypeId::of::<T>()))
        .collect();
    let own_dir = own.parent().unwrap_or(Path::new(""));
    for dep in T::dependencies() {
        if dep.id == TypeId::of::<T>() {
            continue;
        }
        validate_path(&dep.path)?;
        if own == dep.path {
            return Err(ExportError::ConflictingFile(own));
        }
        if names
            .insert(dep.name.clone(), dep.id)
            .is_some_and(|id| id != dep.id)
        {
            return Err(ExportError::NameCollision(dep.name));
        }
        let dep_dir = dep.path.parent().unwrap_or(Path::new(""));
        let own_parts: Vec<_> = own_dir.components().collect();
        let dep_parts: Vec<_> = dep_dir.components().collect();
        let common = own_parts
            .iter()
            .zip(&dep_parts)
            .take_while(|(a, b)| a == b)
            .count();
        let up = own_parts.len() - common;
        let mut module = ".".repeat(up + 1);
        let tail: Vec<_> = dep_parts[common..]
            .iter()
            .map(|c| c.as_os_str().to_string_lossy().into_owned())
            .collect();
        if !tail.is_empty() {
            module.push_str(&tail.join("."));
            module.push('.');
        }
        module.push_str(&dep.path.file_stem().unwrap().to_string_lossy());
        imports.entry(module).or_default().insert(dep.name);
    }
    let mut out = format!(
        "{HEADER}# Rust type: {}\nfrom __future__ import annotations\n\n",
        std::any::type_name::<T>()
    );
    out.push_str(&T::decl());
    out.push('\n');
    for (module, names) in imports {
        out.push_str(&format!(
            "from {module} import {}\n",
            names.into_iter().collect::<Vec<_>>().join(", ")
        ));
    }
    Ok(out)
}

macro_rules! primitive {
    ($($ty:ty => $py:expr),* $(,)?) => {$ (
        impl PY for $ty {
            fn name() -> String { $py.into() }
            fn inline() -> String { $py.into() }
        }
    )*};
}

primitive! {
    bool => "bool", char => "str", String => "str",
    i8 => "int", i16 => "int", i32 => "int", i64 => "int", i128 => "int", isize => "int",
    u8 => "int", u16 => "int", u32 => "int", u64 => "int", u128 => "int", usize => "int",
    f32 => "float", f64 => "float", () => "None",
}

impl<T: PY> PY for Option<T> {
    fn name() -> String {
        Self::inline()
    }
    fn inline() -> String {
        format!("{} | None", T::inline())
    }
    fn referenced_types() -> Vec<Dependency> {
        T::referenced_types()
    }
}

impl<T: PY> PY for Vec<T> {
    fn name() -> String {
        Self::inline()
    }
    fn inline() -> String {
        format!("list[{}]", T::inline())
    }
    fn referenced_types() -> Vec<Dependency> {
        T::referenced_types()
    }
}

impl<T: PY> PY for Box<T> {
    fn name() -> String {
        T::name()
    }
    fn inline() -> String {
        T::inline()
    }
    fn referenced_types() -> Vec<Dependency> {
        T::referenced_types()
    }
}

impl<T: PY, const N: usize> PY for [T; N] {
    fn name() -> String {
        Self::inline()
    }
    fn inline() -> String {
        if N == 0 {
            "tuple[()]".into()
        } else {
            format!("tuple[{}]", vec![T::inline(); N].join(", "))
        }
    }
    fn referenced_types() -> Vec<Dependency> {
        T::referenced_types()
    }
}

impl<K: PY, V: PY> PY for std::collections::HashMap<K, V> {
    fn name() -> String {
        Self::inline()
    }
    fn inline() -> String {
        format!("dict[{}, {}]", K::inline(), V::inline())
    }
    fn referenced_types() -> Vec<Dependency> {
        let mut deps = K::referenced_types();
        deps.extend(V::referenced_types());
        deps
    }
}

impl<K: PY, V: PY> PY for std::collections::BTreeMap<K, V> {
    fn name() -> String {
        Self::inline()
    }
    fn inline() -> String {
        format!("dict[{}, {}]", K::inline(), V::inline())
    }
    fn referenced_types() -> Vec<Dependency> {
        let mut deps = K::referenced_types();
        deps.extend(V::referenced_types());
        deps
    }
}

impl<T: PY> PY for std::collections::HashSet<T> {
    fn name() -> String {
        Self::inline()
    }
    fn inline() -> String {
        format!("set[{}]", T::inline())
    }
    fn referenced_types() -> Vec<Dependency> {
        T::referenced_types()
    }
}

impl<T: PY> PY for std::collections::BTreeSet<T> {
    fn name() -> String {
        Self::inline()
    }
    fn inline() -> String {
        format!("set[{}]", T::inline())
    }
    fn referenced_types() -> Vec<Dependency> {
        T::referenced_types()
    }
}

impl<A: PY, B: PY> PY for (A, B) {
    fn name() -> String {
        Self::inline()
    }
    fn inline() -> String {
        format!("tuple[{}, {}]", A::inline(), B::inline())
    }
    fn referenced_types() -> Vec<Dependency> {
        let mut deps = A::referenced_types();
        deps.extend(B::referenced_types());
        deps
    }
}
