use crate::{ExportError, PY};
use std::fs;
use std::path::Path;

pub(super) const HEADER: &str = "# This file was generated by py-rs. Do not edit.\n";

pub(super) fn module<T: PY + ?Sized>(
    dir: &Path,
    relative: &Path,
    content: &str,
) -> Result<(), ExportError> {
    let path = dir.join(relative);
    match fs::read_to_string(&path) {
        Ok(existing) => {
            let declaration = T::declaration_id();
            let owner = existing.lines().nth(1).unwrap_or_default();
            let same_owner = owner == format!("# Rust type: {declaration}")
                || owner.starts_with(&format!("# Rust type: {declaration}<"));
            if !existing.starts_with(HEADER) || !same_owner {
                return Err(ExportError::ConflictingFile(path));
            }
            if existing == content {
                return Ok(());
            }
        }
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => {}
        Err(err) => return Err(ExportError::Io(err)),
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    create_package_markers(dir, path.parent())?;
    fs::write(path, content)?;
    Ok(())
}

fn create_package_markers(dir: &Path, mut package: Option<&Path>) -> Result<(), ExportError> {
    while let Some(folder) = package {
        if !folder.starts_with(dir) {
            break;
        }
        let marker = folder.join("__init__.py");
        if !marker.exists() {
            fs::write(&marker, "")?;
        }
        if folder == dir {
            break;
        }
        package = folder.parent();
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};

    struct Model;

    impl PY for Model {
        fn name() -> String {
            "Model".into()
        }
        fn inline() -> String {
            "Model".into()
        }
        fn declaration_id() -> &'static str {
            "tests::Model"
        }
    }

    struct TestDir(PathBuf);

    impl TestDir {
        fn new() -> Self {
            let nonce = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("clock before epoch")
                .as_nanos();
            let path =
                std::env::temp_dir().join(format!("py-rs-write-{}-{nonce}", std::process::id()));
            fs::create_dir(&path).expect("create test directory");
            Self(path)
        }
    }

    impl Drop for TestDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    #[test]
    fn writes_packages_and_replaces_only_owned_files() {
        let dir = TestDir::new();
        let relative = Path::new("nested/Model.py");
        let path = dir.0.join(relative);
        let generated = format!("{HEADER}# Rust type: tests::Model\nclass Model: pass\n");
        module::<Model>(&dir.0, relative, &generated).unwrap();
        assert!(dir.0.join("__init__.py").exists());
        assert!(dir.0.join("nested/__init__.py").exists());
        module::<Model>(&dir.0, relative, &generated).unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), generated);

        fs::write(
            &path,
            format!("{HEADER}# Rust type: tests::Model<Legacy>\nold\n"),
        )
        .unwrap();
        module::<Model>(&dir.0, relative, &generated).unwrap();
        assert_eq!(fs::read_to_string(&path).unwrap(), generated);

        for foreign in [
            "hand-written Python\n",
            "# This file was generated by py-rs. Do not edit.\n# Rust type: tests::Other\n",
        ] {
            fs::write(&path, foreign).unwrap();
            assert!(matches!(
                module::<Model>(&dir.0, relative, &generated),
                Err(ExportError::ConflictingFile(_))
            ));
            assert_eq!(fs::read_to_string(&path).unwrap(), foreign);
        }
    }
}
