use super::model::{
    DataclassOptions, DataclassSpec, Declaration, FieldDefault, FieldSpec, StringEnumSpec,
};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

pub(crate) fn render_type(expression: &super::TypeExpr) -> String {
    render_type_with(expression, &NameResolver::default())
}

fn render_type_with(expression: &super::TypeExpr, names: &NameResolver) -> String {
    match expression {
        super::TypeExpr::Name(name) => names
            .model_aliases
            .get(name)
            .cloned()
            .unwrap_or_else(|| name.clone()),
        super::TypeExpr::UnsafeRaw(name) => name.clone(),
        super::TypeExpr::Qualified { module, name } => format!(
            "{}.{name}",
            names
                .module_aliases
                .get(module)
                .map_or(module.as_str(), String::as_str)
        ),
        super::TypeExpr::Subscript { base, args } => format!(
            "{}[{}]",
            render_type_with(base, names),
            args.iter()
                .map(|arg| render_type_with(arg, names))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        super::TypeExpr::Union(items) => items
            .iter()
            .map(|item| render_type_with(item, names))
            .collect::<Vec<_>>()
            .join(" | "),
        super::TypeExpr::Tuple(items) if items.is_empty() => "tuple[()]".into(),
        super::TypeExpr::Tuple(items) => format!(
            "tuple[{}]",
            items
                .iter()
                .map(|item| render_type_with(item, names))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        super::TypeExpr::VariadicTuple(item) => {
            format!("tuple[{}, ...]", render_type_with(item, names))
        }
        super::TypeExpr::Literal(value) => format!("Literal[{}]", python_literal(value)),
    }
}

#[derive(Default)]
struct NameResolver {
    module_aliases: BTreeMap<String, String>,
    model_aliases: BTreeMap<String, String>,
}

impl NameResolver {
    fn for_module(
        module_imports: &BTreeSet<String>,
        model_imports: &[ModelImport],
        declarations: &[Declaration],
    ) -> Self {
        // Reserve names introduced anywhere in the module: deferred annotations
        // are later resolved against the class and module namespaces.
        let declaration_names = declarations
            .iter()
            .map(Declaration::name)
            .map(str::to_owned)
            .collect::<BTreeSet<_>>();
        let field_names = declarations
            .iter()
            .filter_map(|declaration| match declaration {
                Declaration::Dataclass(dataclass) => Some(dataclass.fields.iter()),
                _ => None,
            })
            .flatten()
            .map(|field| field.name.clone())
            .collect::<BTreeSet<_>>();
        let model_names = model_imports
            .iter()
            .flat_map(|import| import.names.iter().cloned())
            .collect::<BTreeSet<_>>();
        let mut occupied = declaration_names
            .iter()
            .chain(&field_names)
            .chain(&model_names)
            .cloned()
            .collect::<BTreeSet<_>>();
        occupied.extend(
            module_imports
                .iter()
                .filter_map(|module| module.split('.').next())
                .map(str::to_owned),
        );

        let mut names = Self::default();
        for module in module_imports {
            let root = module.split('.').next().unwrap_or(module);
            if declaration_names.contains(root)
                || field_names.contains(root)
                || model_names.contains(root)
            {
                let alias = unique_alias(&format!("_py_rs_{root}"), &mut occupied);
                names.module_aliases.insert(module.clone(), alias);
            }
        }
        for name in model_names {
            if field_names.contains(&name) {
                let alias = unique_alias(&format!("_py_rs_{name}"), &mut occupied);
                names.model_aliases.insert(name, alias);
            }
        }
        names
    }
}

fn unique_alias(base: &str, occupied: &mut BTreeSet<String>) -> String {
    let mut candidate = base.to_owned();
    let mut suffix = 2;
    while !occupied.insert(candidate.clone()) {
        candidate = format!("{base}_{suffix}");
        suffix += 1;
    }
    candidate
}

pub(crate) const HEADER: &str = "# This file was generated by rust-py-models. Do not edit.\n";

pub(crate) struct ModelImport {
    pub(crate) module: String,
    pub(crate) names: BTreeSet<String>,
    pub(crate) cyclic: bool,
}

pub(crate) fn render_module(
    owners: &[&str],
    module_imports: &BTreeSet<String>,
    model_imports: &[ModelImport],
    declarations: &[Declaration],
) -> String {
    let owner_line = if let [owner] = owners {
        format!("# Rust type: {owner}\n")
    } else {
        format!("# Rust types: {}\n", owners.join(", "))
    };
    let mut out = format!(
        "{HEADER}{owner_line}# fmt: off\n# ruff: noqa: I001\nfrom __future__ import annotations\n"
    );
    let names = NameResolver::for_module(module_imports, model_imports, declarations);

    let (dataclasses, typing, needs_enum) = required_imports(declarations);
    let has_standard =
        !module_imports.is_empty() || !dataclasses.is_empty() || needs_enum || !typing.is_empty();
    if has_standard {
        out.push('\n');
    }
    for module in module_imports {
        if let Some(alias) = names.module_aliases.get(module) {
            let _ = writeln!(out, "import {module} as {alias}");
        } else {
            let _ = writeln!(out, "import {module}");
        }
    }
    if !dataclasses.is_empty() {
        let _ = writeln!(
            out,
            "from dataclasses import {}",
            dataclasses.into_iter().collect::<Vec<_>>().join(", ")
        );
    }
    if needs_enum {
        out.push_str("from enum import Enum\n");
    }
    if !typing.is_empty() {
        let _ = writeln!(
            out,
            "from typing import {}",
            typing.into_iter().collect::<Vec<_>>().join(", ")
        );
    }
    // A cyclic dependency cannot be imported until this module's declarations
    // exist, or Python observes a partially initialized module.
    let eager = model_imports
        .iter()
        .filter(|import| !import.cyclic)
        .collect::<Vec<_>>();
    if !eager.is_empty() {
        out.push('\n');
        for import in eager {
            write_model_import(&mut out, import, &names, "\n");
        }
    }

    let first_is_assignment = declarations.first().is_some_and(is_assignment);
    out.push_str(if first_is_assignment { "\n" } else { "\n\n" });
    out.push_str(&render_declarations_with(declarations, &names));
    if model_imports.iter().any(|import| import.cyclic) {
        out.push_str("\n\n");
        for import in model_imports.iter().filter(|import| import.cyclic) {
            write_model_import(
                &mut out,
                import,
                &names,
                "  # noqa: E402 - cyclic dependency\n",
            );
        }
    }
    out
}

fn render_declarations_with(declarations: &[Declaration], names: &NameResolver) -> String {
    let mut out = String::new();
    for (index, declaration) in declarations.iter().enumerate() {
        if index > 0 {
            let previous = &declarations[index - 1];
            out.push_str(if is_assignment(previous) && is_assignment(declaration) {
                "\n"
            } else {
                "\n\n\n"
            });
        }
        out.push_str(&render_declaration(declaration, names));
    }
    out.push('\n');
    out
}

fn is_assignment(declaration: &Declaration) -> bool {
    matches!(
        declaration,
        Declaration::TypeVar(_) | Declaration::TypeAlias { .. } | Declaration::NewType { .. }
    )
}

fn render_declaration(declaration: &Declaration, names: &NameResolver) -> String {
    match declaration {
        Declaration::TypeVar(name) => format!("{name} = TypeVar({})", python_literal(name)),
        Declaration::Dataclass(dataclass) => render_dataclass(dataclass, names),
        Declaration::StringEnum(string_enum) => render_string_enum(string_enum),
        Declaration::TypeAlias {
            name,
            target,
            documentation,
        } => render_type_alias(name, target, documentation.as_deref(), names),
        Declaration::NewType {
            name,
            target,
            documentation,
        } => render_assignment(
            documentation.as_deref(),
            format!(
                "{name} = NewType({}, {})",
                python_literal(name),
                render_type_with(target.expression(), names)
            ),
        ),
    }
}

fn render_type_alias(
    name: &str,
    target: &super::TypeSpec,
    documentation: Option<&str>,
    names: &NameResolver,
) -> String {
    const LINE_LENGTH: usize = 88;

    let annotation = render_type_with(target.expression(), names);
    let prefix = format!("{name}: TypeAlias = ");
    let single_line = format!("{prefix}{annotation}");
    if single_line.chars().count() <= LINE_LENGTH {
        return render_assignment(documentation, single_line);
    }

    if annotation.chars().count() + 4 <= LINE_LENGTH {
        return render_assignment(documentation, format!("{prefix}(\n    {annotation}\n)"));
    }

    let super::TypeExpr::Union(items) = target.expression() else {
        return render_assignment(documentation, single_line);
    };
    let mut out = format!("{prefix}(\n");
    for (index, item) in items.iter().enumerate() {
        let separator = if index == 0 { "    " } else { "    | " };
        let _ = writeln!(out, "{separator}{}", render_type_with(item, names));
    }
    out.push(')');
    render_assignment(documentation, out)
}

fn render_dataclass(dataclass: &DataclassSpec, names: &NameResolver) -> String {
    let mut out = dataclass_decorator(dataclass.options);
    let _ = write!(out, "\nclass {}", dataclass.name);
    if !dataclass.type_params.is_empty() {
        let _ = write!(out, "(Generic[{}])", dataclass.type_params.join(", "));
    }
    out.push_str(":\n");
    if let Some(documentation) = &dataclass.documentation {
        let _ = writeln!(out, "    {}", python_literal(documentation));
    }
    if dataclass.fields.is_empty() {
        if dataclass.documentation.is_none() {
            out.push_str("    pass");
        } else {
            out.pop();
        }
    } else {
        for (index, field) in dataclass.fields.iter().enumerate() {
            if index > 0 {
                out.push('\n');
            }
            out.push_str("    ");
            out.push_str(&render_field(field, names));
        }
    }
    out
}

fn render_field(field: &FieldSpec, names: &NameResolver) -> String {
    let mut out = format!(
        "{}: {}",
        field.name,
        render_type_with(field.ty.expression(), names)
    );
    if let Some(FieldDefault::DataclassField { init, value }) = &field.default {
        let value = python_literal(value);
        let _ = write!(
            out,
            " = field(init={}, default={value})",
            if *init { "True" } else { "False" }
        );
    }
    if let Some(documentation) = &field.documentation {
        let _ = write!(out, "\n    {}", python_literal(documentation));
    }
    out
}

fn render_string_enum(string_enum: &StringEnumSpec) -> String {
    let mut out = format!("class {}(str, Enum):\n", string_enum.name);
    if let Some(documentation) = &string_enum.documentation {
        let _ = writeln!(out, "    {}", python_literal(documentation));
    }
    if string_enum.members.is_empty() {
        if string_enum.documentation.is_none() {
            out.push_str("    pass");
        } else {
            out.pop();
        }
    } else {
        for (index, member) in string_enum.members.iter().enumerate() {
            if index > 0 {
                out.push('\n');
            }
            let _ = write!(
                out,
                "    {} = {}",
                member.name,
                python_literal(&member.value)
            );
            if let Some(documentation) = &member.documentation {
                let _ = write!(out, "\n    {}", python_literal(documentation));
            }
        }
    }
    out
}

fn render_assignment(documentation: Option<&str>, assignment: String) -> String {
    let Some(documentation) = documentation else {
        return assignment;
    };
    let comments = documentation
        .lines()
        .map(|line| {
            if line.is_empty() {
                String::from("#")
            } else {
                format!("# {line}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n");
    format!("{comments}\n{assignment}")
}

fn dataclass_decorator(options: DataclassOptions) -> String {
    let mut args = Vec::new();
    for (name, value) in [
        ("frozen", options.frozen),
        ("slots", options.slots),
        ("kw_only", options.kw_only),
    ] {
        if let Some(value) = value {
            args.push(format!("{name}={}", if value { "True" } else { "False" }));
        }
    }
    if args.is_empty() {
        "@dataclass".into()
    } else {
        format!("@dataclass({})", args.join(", "))
    }
}

fn required_imports(
    declarations: &[Declaration],
) -> (BTreeSet<&'static str>, BTreeSet<&'static str>, bool) {
    let mut dataclasses = BTreeSet::new();
    let mut typing = BTreeSet::new();
    let mut needs_enum = false;
    for declaration in declarations {
        match declaration {
            Declaration::TypeVar(_) => {
                typing.insert("TypeVar");
            }
            Declaration::Dataclass(dataclass) => {
                dataclasses.insert("dataclass");
                if !dataclass.type_params.is_empty() {
                    typing.insert("Generic");
                }
                if dataclass.fields.iter().any(|field| field.default.is_some()) {
                    dataclasses.insert("field");
                }
                if dataclass
                    .fields
                    .iter()
                    .any(|field| contains_literal(field.ty.expression()))
                {
                    typing.insert("Literal");
                }
            }
            Declaration::StringEnum(_) => needs_enum = true,
            Declaration::TypeAlias { target, .. } => {
                typing.insert("TypeAlias");
                if contains_literal(target.expression()) {
                    typing.insert("Literal");
                }
            }
            Declaration::NewType { target, .. } => {
                typing.insert("NewType");
                if contains_literal(target.expression()) {
                    typing.insert("Literal");
                }
            }
        }
    }
    (dataclasses, typing, needs_enum)
}

fn contains_literal(expression: &super::TypeExpr) -> bool {
    match expression {
        super::TypeExpr::Literal(_) => true,
        super::TypeExpr::Subscript { base, args } => {
            contains_literal(base) || args.iter().any(contains_literal)
        }
        super::TypeExpr::Union(items) | super::TypeExpr::Tuple(items) => {
            items.iter().any(contains_literal)
        }
        super::TypeExpr::VariadicTuple(item) => contains_literal(item),
        super::TypeExpr::Name(_)
        | super::TypeExpr::Qualified { .. }
        | super::TypeExpr::UnsafeRaw(_) => false,
    }
}

fn write_model_import(out: &mut String, import: &ModelImport, names: &NameResolver, suffix: &str) {
    let imported = import
        .names
        .iter()
        .map(|name| {
            names
                .model_aliases
                .get(name)
                .map_or_else(|| name.clone(), |alias| format!("{name} as {alias}"))
        })
        .collect::<Vec<_>>()
        .join(", ");
    let _ = write!(out, "from {} import {imported}{suffix}", import.module);
}

fn python_literal(value: &str) -> String {
    let delimiter = if value.contains('"') && !value.contains('\'') {
        '\''
    } else {
        '"'
    };
    let mut out = String::new();
    out.push(delimiter);
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' if delimiter == '"' => out.push_str("\\\""),
            '\'' if delimiter == '\'' => out.push_str("\\'"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c.is_control() => {
                let _ = write!(out, "\\u{:04x}", u32::from(c));
            }
            c => out.push(c),
        }
    }
    out.push(delimiter);
    out
}
