"""Generate and check the Python bindings with the active interpreter."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PY_RS = ROOT / "py-rs"
TESTS = PY_RS / "tests"


def run(*args: str, env: dict[str, str] | None = None) -> None:
    subprocess.run(args, cwd=ROOT, env=env, check=True)


def check(bindings: Path) -> None:
    if not (bindings / "__init__.py").is_file() or not (bindings / "User.py").is_file():
        raise SystemExit(f"Bindings are missing from {bindings}")

    env = os.environ.copy()
    env["PY_RS_BINDINGS_ROOT"] = str(bindings.parent)
    env["MYPYPATH"] = str(bindings.parent)
    version = f"{sys.version_info.major}.{sys.version_info.minor}"

    run(sys.executable, "-m", "compileall", "-q", str(bindings), env=env)
    run(
        sys.executable,
        "-m",
        "ruff",
        "check",
        "--select",
        "E402,F401,F821,I",
        str(bindings),
        str(TESTS / "test_generated_bindings.py"),
        str(TESTS / "typecheck_contract.py"),
        str(Path(__file__).resolve()),
        env=env,
    )
    run(
        sys.executable,
        "-m",
        "mypy",
        "--strict",
        "--no-incremental",
        "--python-version",
        version,
        str(bindings),
        str(TESTS / "typecheck_contract.py"),
        env=env,
    )
    run(
        sys.executable,
        "-m",
        "unittest",
        "discover",
        "-s",
        str(TESTS),
        "-p",
        "test_*.py",
        env=env,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--bindings-dir",
        type=Path,
        help="Check bindings generated by an earlier Rust test job",
    )
    args = parser.parse_args()

    if args.bindings_dir is not None:
        check(args.bindings_dir.resolve())
        return

    with tempfile.TemporaryDirectory(prefix="py-rs-test-") as temporary:
        bindings = Path(temporary) / "bindings"
        env = os.environ.copy()
        env["PY_RS_EXPORT_DIR"] = str(bindings)
        run("cargo", "test", "--workspace", "--all-features", "--locked", env=env)
        check(bindings)


if __name__ == "__main__":
    main()
