#![warn(missing_docs)]
#![warn(rustdoc::broken_intra_doc_links)]

//! Generate importable Python model declarations from Rust structs and enums.
//!
//! Derive [`PY`] for model types, then call [`PY::export_all`] to write a root
//! model and its dependencies. Mark roots with `#[py(export)]` and call
//! [`export_all`] to write every registered root to the configured directory.
//! Use [`export_all_to`] when the caller chooses the directory.
//!
//! Generated annotations describe Python-facing shapes.

mod dependency;
mod error;
mod export;
mod hashability;
mod impls;
mod ir;
mod registry;
mod trait_py;

pub use dependency::Dependency;
pub use error::ExportError;
pub use ir::{
    DataclassOptions, DataclassSpec, Declaration, EnumMemberSpec, FieldDefault, FieldSpec,
    ModelSpec, StringEnumSpec, TypeExpr, TypeSpec,
};
pub use registry::{export_all, export_all_to};
pub use rust_py_models_macros::PY;
pub use trait_py::PY;

/// Items referenced by code generated by `#[derive(PY)]`.
#[doc(hidden)]
pub mod __private {
    pub use crate::hashability::check as check_hashability;
    pub use crate::registry::ExportRoot;
    pub use inventory;
}
