#![warn(missing_docs)]
#![warn(rustdoc::broken_intra_doc_links)]

//! Generate importable Python model declarations from Rust structs and enums.
//!
//! Derive [`PY`] for model types, then use [`PY::export_all`] to write a root
//! model and its dependencies. `#[py(export)]` provides the same workflow as a
//! generated Rust test.
//!
//! Generated annotations describe Python-facing shapes. They do not convert
//! Rust values, perform Serde serialization, or validate Python values at runtime.

mod dependency;
mod error;
mod export;
mod hashability;
mod impls;
mod ir;
mod trait_py;

pub use dependency::Dependency;
pub use error::ExportError;
pub use ir::{
    DataclassOptions, DataclassSpec, Declaration, EnumMemberSpec, FieldDefault, FieldSpec,
    ModelSpec, StringEnumSpec, TypeExpr, TypeSpec,
};
pub use rust_py_models_macros::PY;
pub use trait_py::PY;

/// Items referenced by code generated by `#[derive(PY)]`.
#[doc(hidden)]
pub mod __private {
    pub use crate::hashability::check as check_hashability;
}
